name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Variant to build'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - qa
          - release
          - debug


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      run: |
        TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
        mkdir "${TMP_KEYSTORE_FILE_PATH}"
        echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/keystore.jks

    - name: Build with Gradle
      run: ./gradlew assembleRelease
      env:
        ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.inputs.flavor }}-apk
        path: app/build/outputs/apk/${{ github.event.inputs.flavor }}/app-${{ github.event.inputs.flavor }}-unsigned.apk

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/*.apk
