name: Build and Sign APK

on:
  workflow_call:
    inputs:
      variant:
        description: 'Build variant to build'
        required: true
        type: string
    secrets:
      ANDROID_KEYSTORE_BASE64:
        required: true
      ANDROID_KEYSTORE_PASSWORD:
        required: true
      ANDROID_KEY_ALIAS:
        required: true
      ANDROID_KEY_PASSWORD:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Download version code artifact
      id: download_version_code
      uses: actions/download-artifact@v4
      with:
        name: version_code
        path: version_code

    - name: Increment version code
      id: increment_version_code
      run: |
        VERSION_CODE=$(cat version_code/version_code.txt)
        NEW_VERSION_CODE=$((VERSION_CODE + 1))
        echo $NEW_VERSION_CODE > version_code/version_code.txt
        echo "New version code: $NEW_VERSION_CODE"
        echo "VERSION_CODE=$NEW_VERSION_CODE" >> $GITHUB_ENV

    - name: Update version code in build.gradle
      run: |
        sed -i "s/versionCode [0-9]\+/versionCode $VERSION_CODE/" app/build.gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      run: |
        TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
        mkdir "${TMP_KEYSTORE_FILE_PATH}"
        echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/keystore.jks

    - name: Build with Gradle
      run: ./gradlew assemble${{ inputs.variant }}
      env:
        ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-${{ inputs.variant }}-apk
        path: app/build/outputs/apk/${{ inputs.variant }}/*.apk

    - name: Upload updated version code artifact
      uses: actions/upload-artifact@v4
      with:
        name: version_code
        path: version_code/version_code.txt