name: Build and Sign APK

on:
  workflow_call:
    inputs:
      variant:
        description: 'Build variant to build'
        required: true
        type: string
    secrets:
      ANDROID_KEYSTORE_BASE64:
        required: true
      ANDROID_KEYSTORE_PASSWORD:
        required: true
      ANDROID_KEY_ALIAS:
        required: true
      ANDROID_KEY_PASSWORD:
        required: true
      G_TOKEN:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Increment version code
      uses: chkfung/android-version-actions@v1.2.2
      with:
        gradlePath: app/build.gradle
        versionCode: ''
        versionName: '1.0.2'

    - name: Generate build number
      id: buildnumber
      uses: onyxmueller/build-tag-number@v1
      with:
        token: ${{secrets.G_TOKEN}}

      # Now you can pass ${{ steps.buildnumber.outputs.build_number }} to the next steps.
    - name: Another step as an example
      run: echo Tag build number ${{ steps.buildnumber.outputs.build_number }}
    - name: Update version code in build.gradle
      run: |
        sed -i "s/versionCode [0-9]\+/versionCode 99/" app/build.gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      run: |
        TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
        mkdir "${TMP_KEYSTORE_FILE_PATH}"
        echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/keystore.jks

    - name: Build with Gradle
      run: ./gradlew assemble${{ inputs.variant }}
      env:
        ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-${{ inputs.variant }}-apk
        path: app/build/outputs/apk/${{ inputs.variant }}/*.apk