name: Upload to Firebase

on:
  workflow_call:
    inputs:
      variant:
        description: 'Version to upload'
        required: true
        type: string
      apk_path:
        description: 'Path to the signed APK'
        required: true
        type: string
    secrets:
      FIREBASE_STAGING_APP_ID:
        required: false
      FIREBASE_QA_APP_ID:
        required: false
      FIREBASE_RELEASE_APP_ID:
        required: false
      FIREBASE_DEBUG_APP_ID:
        required: false
      CREDENTIAL_FILE_CONTENT:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert variant to lowercase
        id: convert
        run: echo "variant_lowercase=$(echo '${{ inputs.variant }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app-${{ env.variant_lowercase }}-apk
          path: ${{ inputs.apk_path }}

      - name: Set Firebase App ID
        id: set_app_id
        run: |
          case ${{ env.variant_lowercase }} in
            staging)
              echo "app_id=${{ secrets.FIREBASE_STAGING_APP_ID }}" >> $GITHUB_ENV
              ;;
            qa)
              echo "app_id=${{ secrets.FIREBASE_STAGING_APP_ID }}" >> $GITHUB_ENV
              ;;
            debug)
              echo "app_id=${{ secrets.FIREBASE_DEV_APP_ID }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Unknown variant"
              exit 1
              ;;
          esac

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Load Google Service Account
        env:
          CREDENTIAL_FILE_CONTENT: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        run: echo "$CREDENTIAL_FILE_CONTENT" > "$HOME/service-account.json"


      - name: Set Google Application Credentials
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account.json" >> $GITHUB_ENV

      - name: Verify APK exists
        run: |
          ls "$GITHUB_WORKSPACE/app/build/outputs/apk/qa/app-qa.apk"

      - name: Verify APK exists 2
        run: |
          ls "$HOME/service-account.json"

      - name: Decode Google Service Account
        run:
          firebase appdistribution:distribute "${{ inputs.apk_path }}app-${{ env.variant_lowercase }}.apk" \
          --app "${{ env.app_id }}" \
          --groups "testers"
          --debug

      - name: Verify Service Account JSON
        run:
          cat "$HOME/service-account.json"
#      - name: Upload APK to Firebase App Distribution
#        uses: wzieba/Firebase-Distribution-Github-Action@v1
#        with:
#          appId: ${{ env.app_id }}
#          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
#          groups: testers
#          file: ${{ inputs.apk_path }}/app-${{ env.variant_lowercase }}.apk