name: Upload to Firebase

on:
  workflow_call:
    inputs:
      variant:
        description: 'Version to upload'
        required: true
        type: string
      apk_path:
        description: 'Path to the signed APK'
        required: true
        type: string
      appId:
        description: 'Firebase App ID for the selected variant'
        required: true
        type: string
    secrets:
      FIREBASE_TOKEN:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.variant }}-apk
          path: ${{ inputs.apk_path }}

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ inputs.appId }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: ${{ inputs.apk_path }}/app-${{ inputs.variant }}.apk