name: Upload to Firebase

on:
  workflow_call:
    inputs:
      variant:
        description: 'Version to upload'
        required: true
        type: string
      apk_path:
        description: 'Path to the signed APK'
        required: true
        type: string
    secrets:
      FIREBASE_STAGING_APP_ID:
        required: false
      FIREBASE_QA_APP_ID:
        required: false
      FIREBASE_RELEASE_APP_ID:
        required: false
      FIREBASE_DEBUG_APP_ID:
        required: false
      CREDENTIAL_FILE_CONTENT:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert variant to lowercase
        id: convert
        run: echo "variant_lowercase=$(echo '${{ inputs.variant }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app-${{ env.variant_lowercase }}-apk
          path: ${{ inputs.apk_path }}

      - name: Set Firebase App ID
        id: set_app_id
        run: |
          case ${{ env.variant_lowercase }} in
            staging)
              echo "app_id=${{ secrets.FIREBASE_STAGING_APP_ID }}" >> $GITHUB_ENV
              ;;
            qa)
              echo "app_id=${{ secrets.FIREBASE_STAGING_APP_ID }}" >> $GITHUB_ENV
              ;;
            debug)
              echo "app_id=${{ secrets.FIREBASE_DEV_APP_ID }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Unknown variant"
              exit 1
              ;;
          esac

      - name: Find apk file path
        id: find_file
        run: |
          FILE_PATH=$(find . -type f -name "*${{ env.variant_lowercase }}.apk" | head -n 1)
          if [[ -z "$FILE_PATH" ]]; then
          echo "No APK file found"
          exit 1
          fi
          FOLDER_PATH=$(dirname "$FILE_PATH")
          echo "folder_path=$FOLDER_PATH" >> $GITHUB_OUTPUT
      - name: List APK file3
        run: ls -l ${{ steps.find_file.outputs.file_path }}


      - name: Install Ruby
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full
          ruby -v

      - name: Configure local gem directory
        run: |
          echo "GEM_HOME=$HOME/gems" >> $GITHUB_ENV
          echo "BUNDLE_PATH=$HOME/gems" >> $GITHUB_ENV
          echo "PATH=$HOME/gems/bin:$PATH" >> $GITHUB_ENV

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install --path vendor/bundle
        working-directory: ./fastlane

      - name: Load Firebase Service Account
        run: |
          echo "$CREDENTIAL_FILE_CONTENT" > "$HOME/service-account.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account.json" >> $GITHUB_ENV
        env:
          CREDENTIAL_FILE_CONTENT: ${{ secrets.CREDENTIAL_FILE_CONTENT }}


      - name: List APK file
        run: ls -l app/build/outputs/apk/qa/app-qa.apk

      - name: List APK file2
        run: ls -l $GITHUB_WORKSPACE
        working-directory: ./fastlane



      - name: List APK file4
        run: ls -l ${{ steps.find_file.outputs.folder_path }} \


      - name: Distribute APK to Firebase App Distribution via Fastlane
        run: |
          bundle exec fastlane run firebase_app_distribution \
            app:"${{ env.app_id }}" \
            apk_path: ${{ steps.find_file.outputs.folder_path }} \
            groups:"testers"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}

#      - name: Upload APK to Firebase App Distribution
#        uses: wzieba/Firebase-Distribution-Github-Action@v1
#        with:
#          appId: ${{ env.app_id }}
#          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
#          groups: testers
#          file: ${{ inputs.apk_path }}/app-${{ env.variant_lowercase }}.apk