name: Upload to Firebase

on:
  workflow_call:
    inputs:
      variant:
        description: 'Version to upload'
        required: true
        type: string
      apk_path:
        description: 'Path to the signed APK'
        required: true
        type: string
    secrets:
      FIREBASE_STAGING_APP_ID:
        required: false
      FIREBASE_QA_APP_ID:
        required: false
      FIREBASE_RELEASE_APP_ID:
        required: false
      FIREBASE_DEBUG_APP_ID:
        required: false
      CREDENTIAL_FILE_CONTENT:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert variant to lowercase
        id: convert
        run: echo "variant_lowercase=$(echo '${{ inputs.variant }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app-${{ env.variant_lowercase }}-apk
          path: ${{ inputs.apk_path }}

      - name: Set Firebase App ID
        id: set_app_id
        run: |
          case ${{ env.variant_lowercase }} in
            staging)
              echo "app_id=${{ secrets.FIREBASE_STAGING_APP_ID }}" >> $GITHUB_ENV
              ;;
            qa)
              echo "app_id=${{ secrets.FIREBASE_STAGING_APP_ID }}" >> $GITHUB_ENV
              ;;
            debug)
              echo "app_id=${{ secrets.FIREBASE_DEV_APP_ID }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Unknown variant"
              exit 1
              ;;
          esac

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Bundler and dependencies
        run: |
          gem install bundler
          bundle install
        working-directory: ./fastlane

      - name: Load Firebase Service Account
        run: |
          echo "$CREDENTIAL_FILE_CONTENT" > "$HOME/service-account.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account.json" >> $GITHUB_ENV
        env:
          CREDENTIAL_FILE_CONTENT: ${{ secrets.CREDENTIAL_FILE_CONTENT }}


      - name: Distribute APK to Firebase App Distribution via Fastlane
        run: |
          bundle exec fastlane run firebase_app_distribution \
            app:"${{ env.app_id }}" \
            apk_path:"${{ inputs.apk_path }}app-${{ env.variant_lowercase }}.apk" \
            groups:"testers"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        working-directory: ./fastlane

#      - name: Upload APK to Firebase App Distribution
#        uses: wzieba/Firebase-Distribution-Github-Action@v1
#        with:
#          appId: ${{ env.app_id }}
#          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
#          groups: testers
#          file: ${{ inputs.apk_path }}/app-${{ env.variant_lowercase }}.apk