name: Android Manual Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  load-properties:
    uses: ./.github/workflows/wf-init-env.yml
    with:
      variant: Qa
    secrets: inherit

  check-branch:
    uses: ./.github/workflows/wf-check-branch.yml

  check:
    needs: [load-properties, check-branch]
    uses: ./.github/workflows/unit_test_and_lint.yml
    with:
      variant: Qa
    secrets: inherit

  build:
    needs: [load-properties, check-branch]
    uses: ./.github/workflows/build_and_sign.yml
    with:
      variant: Qa
    secrets: inherit

  upload_to_firebase:
    needs: [build, check]
    uses: ./.github/workflows/firebase_upload.yml
    with:
      variant: Qa
      apk_path: app/build/outputs/apk/qa/
    secrets: inherit
