name: Android Manual Build

on:
  workflow_dispatch:
    inputs:
      variant:
        description: 'Variant to build'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - qa
          - Release
          - debug


jobs:
  build:
    uses: ./.github/workflows/build_and_sign.yml
    with:
      variant: ${{ github.event.inputs.variant }}
    secrets: inherit

  upload_to_firebase:
    needs: build
    uses: ./.github/workflows/upload_to_firebase.yml
    with:
      flavor: ${{ github.event.inputs.variant }}
      apk_path: app/build/outputs/apk/${{ github.event.inputs.variant }}/release
    secrets: inherit
