name: Android Manual Build

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Variant to build'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - qa
          - release
          - debug

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assemble${{ github.event.inputs.flavor }}
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ github.event.inputs.flavor }}-apk
          path: app/build/outputs/apk/${{ github.event.inputs.flavor }}/*.apk
