name: Pipeline QA

on:
  pull_request:
    branches: [ "main" ]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - name: Print Token
      run: echo ${{ secrets.GITHUB_TOKEN }}
  build:
    uses: ./.github/workflows/build_and_sign.yml
    with:
      variant: qa
    secrets: inherit
