name: Pipeline QA

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: ./.github/workflows/build_and_sign.yml
    with:
      variant: qa
    secrets: inherit
  upload_to_firebase:
    needs: build
    uses: ./.github/workflows/firebase_upload.yml
    with:
      variant: qa
      apk_path: app/build/outputs/apk/qa/
      appId: ${{ secrets.FIREBASE_STAGING_APP_ID }}
    secrets: inherit
