name: Pipeline QA

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  load-properties:
    uses: ./.github/workflows/wf-init-env.yml
    with:
      variant: Qa


