name: Unit tests and Lint

on:
  workflow_call:
    inputs:
      variant:
        description: 'Build variant'
        required: true
        type: string

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Android Lint
        run: ./gradlew lint${{ inputs.variant }}

      - name: Upload lint results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: lint-results
          path: app/build/reports/lint-results-${{ inputs.variant }}.html

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test${{ inputs.variant }}UnitTest

      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-results
          path: app/build/test-results/test${{ inputs.variant }}UnitTest
