name: Initialize version code

on:
  workflow_dispatch:
    inputs:
      number:
        description: 'Init version code number'
        required: true
        default: 1
        type: number

jobs:
  initialize:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create version_code.txt
      run: |
        echo "${{ inputs.number }}" > version_code.txt

    - name: Upload version code artifact
      uses: actions/upload-artifact@v4
      with:
        name: version_code
        path: version_code.txt