name: Init environment properties

on:
  workflow_call:
    inputs:
      variant:
        required: true
        type: string

jobs:
  load-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load Properties File
        env:
          SECRET_NAME: ${{ inputs.variant }}_PROPERTIES_BASE64
        run: |
          
          SECRET_VALUE=$(echo "${{ secrets[env.SECRET_NAME] }}")
          FILENAME="${{ inputs.variant,, }}.properties"
          echo "$SECRET_VALUE" | base64 --decode > $FILENAME
          # Dodatkowe logowanie do debugowania
          echo "Generated FILENAME: $FILENAME"
          ls -lah
          pwd

      - name: Upload Properties File
        uses: actions/upload-artifact@v4
        with:
          name: properties-file
          path: $FILENAME

