name: Init environment properties

on:
  workflow_call:
    inputs:
      variant:
        required: true
        type: string

jobs:
  load-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load Properties File
        env:
          SECRET_NAME: ${{ inputs.variant }}_PROPERTIES_BASE64
        run: |
          VARIANT_LOWERCASE=$(echo "${{ inputs.variant }}" | tr '[:upper:]' '[:lower:]')
          VARIANT_UPPERCASE=$(echo "${{ inputs.variant }}" | tr '[:lower:]' '[:upper:]')
          SECRET_VALUE=$(echo "${{ secrets["${VARIANT_UPPERCASE}_PROPERTIES_BASE64"] }}")
          FILENAME="${VARIANT_LOWERCASE}.properties"
          echo "$SECRET_VALUE" | base64 --decode > $FILENAME
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV
          echo "Generated FILENAME: $FILENAME"
          echo "Generated SECRET_VALUE: $SECRET_VALUE"
          ls -lah
          pwd

      - name: test
        run: |
          echo "Generated FILENAME: $FILENAME"
      - name: Upload Properties File
        uses: actions/upload-artifact@v4
        with:
          name: properties-file
          path: ${{ env.FILENAME }}

