name: Init environment properties

on:
  workflow_call:
    inputs:
      variant:
        required: true
        type: string

jobs:
  load-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load Properties File
        run: |
          VARIANT_LOWERCASE=$(echo "$VARIANT" | tr '[:upper:]' '[:lower:]')
          VARIANT_UPPERCASE=$(echo "$VARIANT" | tr '[:lower:]' '[:upper:]')
          
          if [ "$VARIANT_LOWERCASE" == "debug" ]; then
            SECRET_VALUE=${{ secrets.DEBUG_PROPERTIES_BASE64 }}
          elif [ "$VARIANT_LOWERCASE" == "qa" ]; then
            SECRET_VALUE=${{ secrets.QA_PROPERTIES_BASE64 }}
          elif [ "$VARIANT_LOWERCASE" == "release" ]; then
            SECRET_VALUE=${{ secrets.RELEASE_PROPERTIES_BASE64 }}
          else
            echo "Error: Unsupported variant '${VARIANT}'"
            exit 1
          fi

          FILENAME="${VARIANT_LOWERCASE}.properties"
          echo "$SECRET_VALUE" | base64 --decode > $FILENAME
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV
          echo "Generated FILENAME: $FILENAME"
          echo "Generated SECRET_VALUE: $SECRET_VALUE"
          ls -lah
          pwd

      - name: test
        run: |
          echo "Generated FILENAME: $FILENAME"
      - name: Upload Properties File
        uses: actions/upload-artifact@v4
        with:
          name: properties-file
          path: ${{ env.FILENAME }}

